services:

  order-service:
    build:
      context: ./demo
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: "order-service"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=order-service,env=dev"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_TRACES_EXPORTER: "otlp"
    ports:
      - "8088:8088"
    depends_on:
      - collector

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.91.0
    command:
      - --config=/etc/otelcol-contrib/otel-config.yml
    volumes:
      - ./docker/collector/otel-config.yml:/etc/otelcol-contrib/otel-config.yml
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http/protobuf receiver
      - "8889" # Prometheus exporter metrics
    depends_on:
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: on-failure
    # https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations
    command:
      # See feature flags: https://prometheus.io/docs/prometheus/latest/feature_flags/
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 10
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - collector

  tempo:
    image: grafana/tempo:2.8.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3200/api/echo || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 10
    ports:
      - "3200:3200"
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml:ro

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      interval: 5s
      timeout: 1s
      retries: 10
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/local-config.yaml:/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 10
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/datasources/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
      - ./docker/grafana/provisioning/dashboards/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki
      - tempo
volumes:
  grafana-storage:

